// Generated by CIRCT firtool-1.62.0
module ChaChaQuarterRound(
  input  [31:0] io_a_in,
                io_b_in,
                io_c_in,
                io_d_in,
  output [31:0] io_a_out,
                io_b_out,
                io_c_out,
                io_d_out
);

  wire [31:0] _rotator_8_io_val_out;
  wire [31:0] _rotator_12_io_val_out;
  wire [31:0] _rotator_16_io_val_out;
  wire [31:0] _a_1_T = io_a_in + io_b_in;
  wire [31:0] _c_1_T = io_c_in + _rotator_16_io_val_out;
  wire [31:0] _a_2_T = _a_1_T + _rotator_12_io_val_out;
  wire [31:0] _c_2_T = _c_1_T + _rotator_8_io_val_out;
  ChaCha_Shifter rotator_16 (
    .io_val_in  (_a_1_T ^ io_d_in),
    .io_val_out (_rotator_16_io_val_out)
  );
  ChaCha_Shifter_1 rotator_12 (
    .io_val_in  (_c_1_T ^ io_b_in),
    .io_val_out (_rotator_12_io_val_out)
  );
  ChaCha_Shifter_2 rotator_8 (
    .io_val_in  (_a_2_T ^ _rotator_16_io_val_out),
    .io_val_out (_rotator_8_io_val_out)
  );
  ChaCha_Shifter_3 rotator_7 (
    .io_val_in  (_rotator_12_io_val_out ^ _c_2_T),
    .io_val_out (io_b_out)
  );
  assign io_a_out = _a_2_T;
  assign io_c_out = _c_2_T;
  assign io_d_out = _rotator_8_io_val_out;
endmodule

