// Generated by CIRCT firtool-1.62.0
module ChaCha_Engine(
  input         clock,
                reset,
  input  [31:0] io_key_0,
                io_key_1,
                io_key_2,
                io_key_3,
                io_key_4,
                io_key_5,
                io_key_6,
                io_key_7,
                io_nonce_0,
                io_nonce_1,
                io_nonce_2,
                io_position,
  output [31:0] io_keystream_0,
                io_keystream_1,
                io_keystream_2,
                io_keystream_3,
                io_keystream_4,
                io_keystream_5,
                io_keystream_6,
                io_keystream_7,
                io_keystream_8,
                io_keystream_9,
                io_keystream_10,
                io_keystream_11,
                io_keystream_12,
                io_keystream_13,
                io_keystream_14,
                io_keystream_15,
  input         io_push,
                io_run
);

  wire [31:0] _QR4_io_a_out;
  wire [31:0] _QR4_io_b_out;
  wire [31:0] _QR4_io_c_out;
  wire [31:0] _QR4_io_d_out;
  wire [31:0] _QR3_io_a_out;
  wire [31:0] _QR3_io_b_out;
  wire [31:0] _QR3_io_c_out;
  wire [31:0] _QR3_io_d_out;
  wire [31:0] _QR2_io_a_out;
  wire [31:0] _QR2_io_b_out;
  wire [31:0] _QR2_io_c_out;
  wire [31:0] _QR2_io_d_out;
  wire [31:0] _QR1_io_a_out;
  wire [31:0] _QR1_io_b_out;
  wire [31:0] _QR1_io_c_out;
  wire [31:0] _QR1_io_d_out;
  wire [31:0] _ram_io_out_0;
  wire [31:0] _ram_io_out_1;
  wire [31:0] _ram_io_out_2;
  wire [31:0] _ram_io_out_3;
  wire [31:0] _ram_io_out_4;
  wire [31:0] _ram_io_out_5;
  wire [31:0] _ram_io_out_6;
  wire [31:0] _ram_io_out_7;
  wire [31:0] _ram_io_out_8;
  wire [31:0] _ram_io_out_9;
  wire [31:0] _ram_io_out_10;
  wire [31:0] _ram_io_out_11;
  wire [31:0] _ram_io_out_12;
  wire [31:0] _ram_io_out_13;
  wire [31:0] _ram_io_out_14;
  wire [31:0] _ram_io_out_15;
  wire [15:0] _GEN = {16{io_run}} | {16{io_push}};
  ChaChaRamEn ram (
    .clock     (clock),
    .reset     (reset),
    .io_in_0   (io_push ? 32'h61707865 : _QR1_io_a_out),
    .io_in_1   (io_push ? 32'h3320646E : _QR4_io_a_out),
    .io_in_2   (io_push ? 32'h79622D32 : _QR3_io_a_out),
    .io_in_3   (io_push ? 32'h6B206574 : _QR2_io_a_out),
    .io_in_4   (io_push ? io_key_0 : _QR2_io_b_out),
    .io_in_5   (io_push ? io_key_1 : _QR1_io_b_out),
    .io_in_6   (io_push ? io_key_2 : _QR4_io_b_out),
    .io_in_7   (io_push ? io_key_3 : _QR3_io_b_out),
    .io_in_8   (io_push ? io_key_4 : _QR3_io_c_out),
    .io_in_9   (io_push ? io_key_5 : _QR2_io_c_out),
    .io_in_10  (io_push ? io_key_6 : _QR1_io_c_out),
    .io_in_11  (io_push ? io_key_7 : _QR4_io_c_out),
    .io_in_12  (io_push ? io_position : _QR4_io_d_out),
    .io_in_13  (io_push ? io_nonce_0 : _QR3_io_d_out),
    .io_in_14  (io_push ? io_nonce_1 : _QR2_io_d_out),
    .io_in_15  (io_push ? io_nonce_2 : _QR1_io_d_out),
    .io_en_0   (_GEN[0]),
    .io_en_1   (_GEN[1]),
    .io_en_2   (_GEN[2]),
    .io_en_3   (_GEN[3]),
    .io_en_4   (_GEN[4]),
    .io_en_5   (_GEN[5]),
    .io_en_6   (_GEN[6]),
    .io_en_7   (_GEN[7]),
    .io_en_8   (_GEN[8]),
    .io_en_9   (_GEN[9]),
    .io_en_10  (_GEN[10]),
    .io_en_11  (_GEN[11]),
    .io_en_12  (_GEN[12]),
    .io_en_13  (_GEN[13]),
    .io_en_14  (_GEN[14]),
    .io_en_15  (_GEN[15]),
    .io_out_0  (_ram_io_out_0),
    .io_out_1  (_ram_io_out_1),
    .io_out_2  (_ram_io_out_2),
    .io_out_3  (_ram_io_out_3),
    .io_out_4  (_ram_io_out_4),
    .io_out_5  (_ram_io_out_5),
    .io_out_6  (_ram_io_out_6),
    .io_out_7  (_ram_io_out_7),
    .io_out_8  (_ram_io_out_8),
    .io_out_9  (_ram_io_out_9),
    .io_out_10 (_ram_io_out_10),
    .io_out_11 (_ram_io_out_11),
    .io_out_12 (_ram_io_out_12),
    .io_out_13 (_ram_io_out_13),
    .io_out_14 (_ram_io_out_14),
    .io_out_15 (_ram_io_out_15)
  );
  ChaChaQuarterRound QR1 (
    .io_a_in  (_ram_io_out_0),
    .io_b_in  (_ram_io_out_4),
    .io_c_in  (_ram_io_out_8),
    .io_d_in  (_ram_io_out_12),
    .io_a_out (_QR1_io_a_out),
    .io_b_out (_QR1_io_b_out),
    .io_c_out (_QR1_io_c_out),
    .io_d_out (_QR1_io_d_out)
  );
  ChaChaQuarterRound QR2 (
    .io_a_in  (_ram_io_out_1),
    .io_b_in  (_ram_io_out_5),
    .io_c_in  (_ram_io_out_9),
    .io_d_in  (_ram_io_out_13),
    .io_a_out (_QR2_io_a_out),
    .io_b_out (_QR2_io_b_out),
    .io_c_out (_QR2_io_c_out),
    .io_d_out (_QR2_io_d_out)
  );
  ChaChaQuarterRound QR3 (
    .io_a_in  (_ram_io_out_2),
    .io_b_in  (_ram_io_out_6),
    .io_c_in  (_ram_io_out_10),
    .io_d_in  (_ram_io_out_14),
    .io_a_out (_QR3_io_a_out),
    .io_b_out (_QR3_io_b_out),
    .io_c_out (_QR3_io_c_out),
    .io_d_out (_QR3_io_d_out)
  );
  ChaChaQuarterRound QR4 (
    .io_a_in  (_ram_io_out_3),
    .io_b_in  (_ram_io_out_7),
    .io_c_in  (_ram_io_out_11),
    .io_d_in  (_ram_io_out_15),
    .io_a_out (_QR4_io_a_out),
    .io_b_out (_QR4_io_b_out),
    .io_c_out (_QR4_io_c_out),
    .io_d_out (_QR4_io_d_out)
  );
  assign io_keystream_0 = _QR1_io_a_out;
  assign io_keystream_1 = _QR4_io_a_out;
  assign io_keystream_2 = _QR3_io_a_out;
  assign io_keystream_3 = _QR2_io_a_out;
  assign io_keystream_4 = _QR2_io_b_out;
  assign io_keystream_5 = _QR1_io_b_out;
  assign io_keystream_6 = _QR4_io_b_out;
  assign io_keystream_7 = _QR3_io_b_out;
  assign io_keystream_8 = _QR3_io_c_out;
  assign io_keystream_9 = _QR2_io_c_out;
  assign io_keystream_10 = _QR1_io_c_out;
  assign io_keystream_11 = _QR4_io_c_out;
  assign io_keystream_12 = _QR4_io_d_out;
  assign io_keystream_13 = _QR3_io_d_out;
  assign io_keystream_14 = _QR2_io_d_out;
  assign io_keystream_15 = _QR1_io_d_out;
endmodule

